### ISSUE TITLE
support for nifi 1.0

### ISSUE THREAD

**Issue by freeeve** [jonathantelfer/nifi-neo4j#1]
I'm guessing by the dates and such that this is built for an older version of nifi. I'm getting an error about logging, screenshot below. I may be able to follow up with a PR--thanks for this!

![image](https://cloud.githubusercontent.com/assets/882560/18802529/5678ee9e-81b7-11e6-96ae-e16a8c7c0368.png)

**Comment by jonathantelfer** [comment]
Hi Eve. Looks like the way the logger components were structured in NiFi was refactored back in April.

I've got a dev build updated to NiFi 1.0 that works, I'll release it when I've looked at whether it's a good opportunity to update the Neo4j Bolt driver version to 1.1. Look out for it today or tomorrow.

**Comment by jonathantelfer** [comment]
Hi Eve. I've just released an updated version with NiFi 1.0 support. Binaries are on the releases page.
