### ISSUE TITLE
NiFi-Neo4j Connectivity Issues

### ISSUE THREAD

**Issue by dale-chang91** [jonathantelfer/nifi-neo4j#2]
Hello,

I have this architectural curiosity that I was hoping you could help me figure out.

My host computer is Windows 8 and it runs RHEL on VMs in Hyper-V manager. In Linux, I have HDP NiFi (1.0.0.2.0.1.0-12) on a Hadoop (Hortonworks) cluster; Neo4j Enterprise Edition is on Windows.

I have performed these configurations in Windows Neo4j:
- neo4j.conf and specified Neo4j to listen on the public domain: dbms.connector.bolt.listen_address=0.0.0.0.7687
- Opened settings from the Neo4j browser and modified the URL to bolt://(windows.ip.address):7687 instead of localhost:7687

And these changes in Linux NiFi:
- Created a Neo4jBoltSessionPool that is connected to the bolt address specified above
- Created a PutCypher NiFi processor that uses the aforementioned SessionPool and a cypher query to LOAD CSV WITH HEADERS ${file_path}

However, NiFi says "cannot connect to (windows ip) at port 7867, ensure the database is running and that there is a working connection" 

Have I configured everything correctly and it's just an issue with bolt protocol?

**Comment by jonathantelfer** [comment]
Hi there

Sorry, but I don't know what might be going on with that network configuration. The only thing I can suggest is to check that you can access the Neo4j web interface from the Linux guest.
